phpVersion: 7.4
phpMode: fpm

includeModules:
#   - http

#   - amqp
#   - apcu
#   - bcmath
#   - blackfire
#   - bz2
#   - calendar
#   - curl
#   - dba
#   - enchant
#   - exif
#   - gd
#   - gettext
#   - gmp
#   - igbinary
#   - imagick
#   - imap
#   - intl
#   - ioncube
#   - ldap
#   - maxminddb
#   - mbstring
#   - mcrypt
#   - memcached
#   - memcache
#   - mongodb
#   - msgpack
#   - mysqli
#   - oauth
#   - opcache
#   - pcntl
#   - pdo_dblib
#   - pdo_mysql
#   - pdo_pgsql
#   - pdo_sqlsrv
#   - pgsql
#   - phalcon
#   - propro
#   - pspell
#   - psr
#   - raphf
#   - rdkafka
#   - redis
#   - shmop
#   - snmp
#   - soap
#   - sockets
#   - solr
#   - sqlsrv
#   - ssh2
#   - swoole
#   - sysvmsg
#   - sysvsem
#   - sysvshm
#   - tidy
#   - uploadprogress
#   - vips
#   - xdebug
#   - xlswriter
#   - xmlrpc
#   - xsl
#   - yaml
   - zip