apiVersion: dockerfileGenerator.io/v1beta1
kind: ModuleMap
data:
   phpVersion: "7.4"
   phpMode: cli
   includeModules:
      - mcrypt
      - bcmath
      - sockets
      - intl
      - amqp
      - redis
      - zip
      - mysqli
      - pdo_mysql
      - opcache
      - memcache
      - curl
      - mbstring
      - gd
      - xml
      - soap
      - mongodb
      - maxminddb
